import { existsSync, readFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const DEFAULT_SLOTS = JSON.parse(readFileSync(join(__dirname, "slots.json"), "utf8"));

function loadRegistry() {
  return JSON.parse(readFileSync(join(__dirname, "registry.json"), "utf8"));
}

export function findProjectRoot(startDir = process.cwd()) {
  let dir = startDir;
  while (true) {
    if (existsSync(join(dir, "dev-ports.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error(`No dev-ports.json found from ${startDir}`);
    }
    dir = parent;
  }
}

export function readProjectConfig(projectRoot) {
  const cfg = JSON.parse(readFileSync(join(projectRoot, "dev-ports.json"), "utf8"));
  const project = cfg.project ?? basename(projectRoot);
  return { project, base: cfg.base, slots: cfg.slots };
}

function resolveBase(projectRoot, projectName) {
  const configPath = join(projectRoot, "dev-ports.json");
  let slotOverrides;
  if (existsSync(configPath)) {
    const cfg = readProjectConfig(projectRoot);
    if (cfg.base != null) return { base: cfg.base, slots: cfg.slots };
    projectName = cfg.project;
    slotOverrides = cfg.slots;
  }

  const registry = loadRegistry();
  const entry = registry[projectName];
  if (!entry) {
    throw new Error(`Project "${projectName}" is not registered in dev-ports/registry.json`);
  }
  const base = typeof entry === "number" ? entry : entry.base;
  if (!Number.isInteger(base) || base < 1 || base > 999) {
    throw new Error(`Invalid dev port base ${base} for project "${projectName}"`);
  }
  return { base, slots: slotOverrides ?? (typeof entry === "object" ? entry.slots : undefined) };
}

export function projectRootForName(projectName) {
  const registry = loadRegistry();
  const entry = registry[projectName];
  if (!entry) throw new Error(`Project "${projectName}" is not registered in dev-ports/registry.json`);
  const dir = typeof entry === "object" ? entry.dir : projectName;
  if (!dir || dir === ".") return join(__dirname, "..");
  return join(__dirname, "..", dir);
}

export function resolveFromDir(startDir = process.cwd()) {
  const projectRoot = findProjectRoot(startDir);
  const { project } = readProjectConfig(projectRoot);
  return resolveDevPorts(projectRoot, project);
}

export function formatEnvPorts(resolved) {
  const { env } = resolved;
  return [
    "# Generated by dev-ports/sync-env.mjs — do not edit",
    `DEV_PORT_BASE=${env.DEV_PORT_BASE}`,
    `BACKEND_PORT=${env.BACKEND_PORT}`,
    `FRONTEND_PORT=${env.FRONTEND_PORT}`,
    `FRONTEND3_PORT=${env.FRONTEND3_PORT}`,
    `FRONTEND_ORIGIN=${env.FRONTEND_ORIGIN}`,
    `VITE_API_BASE_URL=${env.VITE_API_BASE_URL}`,
    "",
  ].join("\n");
}

export function resolveDevPorts(projectRoot, projectName) {
  const { base, slots: slotOverrides } = resolveBase(projectRoot, projectName);
  const slots = { ...DEFAULT_SLOTS, ...slotOverrides };

  const ports = {};
  for (const [name, offset] of Object.entries(slots)) {
    if (typeof offset !== "number") continue;
    if (offset < 0 || offset > 99) {
      throw new Error(`Slot "${name}" offset ${offset} is outside 0-99 for base ${base}`);
    }
    ports[name] = base * 100 + offset;
  }

  const backend = ports.backend;
  const frontend = ports.frontend;

  return {
    project: projectName,
    projectRoot,
    base,
    range: { start: base * 100, end: base * 100 + 99 },
    ports,
    env: {
      DEV_PORT_BASE: String(base),
      PORT: String(backend),
      BACKEND_PORT: String(backend),
      FRONTEND_PORT: String(frontend),
      FRONTEND3_PORT: String(ports.frontend3),
      FRONTEND_ORIGIN: `http://localhost:${frontend}`,
      VITE_API_BASE_URL: `http://localhost:${backend}`,
    },
  };
}

export function listProjects() {
  const registry = loadRegistry();
  return Object.entries(registry).map(([name, entry]) => {
    const root = projectRootForName(name);
    const resolved = resolveDevPorts(root, name);
    return { name, dir: typeof entry === "object" ? entry.dir : name, ...resolved };
  });
}
